### ISSUE TITLE
Cannot install Curry.jl

### ISSUE THREAD

**Issue by vsoler** [Orbots/Curry.jl#3]
I try to install Curry.jl with the package manager, but it doesn't find it.

`(@v1.8) pkg> add Curry
ERROR: The following package names could not be resolved:
 * Curry (not found in project, manifest or registry)`

What can I do to install the Curry package?

**Comment by Orbots** [comment]
Looks like Curry.jl hasn't been updated to the new standards for the General Registry.

You can always add it directly though.   ]add https://github.com/Orbots/Curry.jl

**Comment by Orbots** [comment]
@JuliaRegistrator register

**Comment by Orbots** [comment]
Package is registered in General again.  Performance will be a impacted since we can't use generated functions anymore.  Not that you should be using this for performance sensitive inner loops in any case.
